{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-faviconplease
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/faviconPlease_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/faviconPlease/faviconPlease_{{ version }}.tar.gz
  sha256: b8be632e23e2c843a889b53ac2a4b77dea7f580b65778f12075216467c0a25e1

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-xml2
  run:
    - r-base
    - r-xml2

test:
  commands:
    - $R -e "library('faviconPlease')"           # [not win]
    - "\"%R%\" -e \"library('faviconPlease')\""  # [win]

about:
  home: https://github.com/jdblischak/faviconPlease
  license: MIT
  summary: Finds the URL to the 'favicon' for a website. This is useful if you want to display the 'favicon' in an HTML document or web application, especially if the website is behind a firewall.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - jdblischak

# Package: faviconPlease
# Title: Find the URL to the 'Favicon' for a Website
# Version: 0.1.1
# Authors@R: person(given = "John", family = "Blischak", role = c("aut", "cre"), email = "jdblischak@gmail.com")
# Description: Finds the URL to the 'favicon' for a website. This is useful if you want to display the 'favicon' in an HTML document or web application, especially if the website is behind a firewall.
# URL: https://github.com/jdblischak/faviconPlease
# BugReports: https://github.com/jdblischak/faviconPlease/issues
# Imports: utils, xml2
# Suggests: httr, tinytest, ttdo
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-01-11 15:12:22 UTC; jdblischak
# Author: John Blischak [aut, cre]
# Maintainer: John Blischak <jdblischak@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-01-14 09:40:08 UTC
